apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: newresource-controller
  namespace: newresource-system
  labels:
    app.kubernetes.io/name: newresource-controller
    app.kubernetes.io/component: controller
    app.kubernetes.io/part-of: newresource-operator
rules:
- apiGroups:
  - "apps.newresource.com"
  resources:
  - "newresources"
  verbs:
  - "get"
  - "list"
  - "watch"
  - "create"
  - "update"
  - "patch"
  - "delete"
- apiGroups:
  - "apps.newresource.com"
  resources:
  - "newresources/status"
  verbs:
  - "get"
  - "update"
  - "patch"
- apiGroups:
  - "coordination.k8s.io"
  resources:
  - "leases"
  verbs:
  - "get"
  - "list"
  - "watch"
  - "create"
  - "update"
  - "patch"
  - "delete"
- apiGroups:
  - ""
  resources:
  - "events"
  verbs:
  - "create"
  - "patch"
- apiGroups:
  - "coordination.k8s.io"
  resources:
  - "leases"
  verbs:
  - "get"
  - "list"
  - "watch"
  - "create"
  - "update"
  - "patch"
  - "delete"