//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be nil, read-only, or a
// T instance. out must be non-nil, writable T instance.
func (in *NewResource) DeepCopyInto(out *NewResource) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NewResource.
func (in *NewResource) DeepCopy() *NewResource {
	if in == nil {
		return nil
	}
	out := new(NewResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NewResource) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be nil, read-only, or a
// T instance. out must be non-nil, writable T instance.
func (in *NewResourceSpec) DeepCopyInto(out *NewResourceSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NewResourceSpec.
func (in *NewResourceSpec) DeepCopy() *NewResourceSpec {
	if in == nil {
		return nil
	}
	out := new(NewResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be nil, read-only, or a
// T instance. out must be non-nil, writable T instance.
func (in *NewResourceStatus) DeepCopyInto(out *NewResourceStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NewResourceStatus.
func (in *NewResourceStatus) DeepCopy() *NewResourceStatus {
	if in == nil {
		return nil
	}
	out := new(NewResourceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be nil, read-only, or a
// T instance. out must be non-nil, writable T instance.
func (in *NewResourceList) DeepCopyInto(out *NewResourceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NewResource, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NewResourceList.
func (in *NewResourceList) DeepCopy() *NewResourceList {
	if in == nil {
		return nil
	}
	out := new(NewResourceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NewResourceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
